import type { Country } from "./types";

export const countries: Country[] = [
  {
    slug: "kenya",
    name: "Kenya",
    iso2: "KE",
    region: "East Africa",
    h1: "Sandwich Panel Export to Kenya — Cold Storage and Industrial",
    seoTitle: "Export Sandwich Panels to Kenya | PHOENIXX",
    metaDescription:
      "PUF and PIR sandwich panels exported from India to Kenya. Mombasa port delivery, Nairobi and Athi River projects. Request a quote.",
    portsOfEntry: ["Mombasa (Kilindini Port)"],
    majorCities: ["nairobi", "athi-river", "mombasa"],
    industrialZones: ["athi-river-industrial-park"],
    demandDrivers: [
      "Cold storage capacity is expanding around Nairobi and Mombasa as food retail and horticulture exports grow — new chiller and freezer rooms are a common enquiry from our Kenya buyers.",
      "Athi River and the Nairobi industrial corridor have active warehouse and factory construction where insulated roof and wall panels are specified.",
      "Fish processing and meat cold chain projects along the coast generate demand for cam-lock cold room kits shipped through Mombasa.",
    ],
    relevantProducts: ["puf-panels", "pir-panels", "cold-room-panels", "industrial-doors"],
    relevantIndustries: ["cold-storage", "food-processing", "warehousing-logistics", "dairy"],
    logisticsNotes:
      "Primary port of entry is Mombasa (Kilindini). Transit time from Indian west coast ports is typically 18–25 days. Containers clear through Kenya Revenue Authority (KRA) at Mombasa; inland delivery to Nairobi is 1–2 days by road (approximately 480 km). We coordinate with your clearing agent and share shipping documents — commercial invoice, packing list, bill of lading and certificate of origin — before the vessel arrives.",
    documentationNotes:
      "Kenya requires an Import Declaration Form (IDF) before shipment. Your clearing agent applies for the IDF through the Kenya TradeNet system. PVoC (Pre-Export Verification of Conformity) may apply depending on product classification — confirm with your agent before we dispatch. We provide all standard export documents from India including GST invoice and shipping bill.",
    faqs: [
      {
        question: "Which port do panels arrive at in Kenya?",
        answer:
          "Mombasa (Kilindini Port) is the main entry point for containerised panel shipments from India. Inland container depots (ICDs) in Nairobi are an option for some consignments — your clearing agent can advise based on the final delivery location.",
      },
      {
        question: "How long does customs clearance take in Mombasa?",
        answer:
          "With complete documentation and a responsive clearing agent, clearance typically takes 3–7 working days after vessel arrival. Delays happen when IDF or PVoC paperwork is incomplete — start the import process before the container sails.",
      },
      {
        question: "Can you deliver panels to Nairobi directly?",
        answer:
          "We deliver to Mombasa port (CIF) or ex-works from India (FOB). Inland transport from Mombasa to Nairobi is arranged by your clearing agent or a local haulier. We can recommend logistics contacts if needed.",
      },
      {
        question: "What import duties apply to sandwich panels in Kenya?",
        answer:
          "Duty rates depend on HS classification and the panel specification. Your clearing agent calculates the exact landed cost. We provide the commercial invoice with product description and HS code suggestion for your agent to verify.",
      },
      {
        question: "Do you have a local office or stock in Kenya?",
        answer:
          "We export from India on a made-to-order basis. We do not maintain local stock in Kenya. Lead time is manufacturing (2–4 weeks) plus shipping (18–25 days). Plan your project timeline accordingly.",
      },
      {
        question: "What panel types do Kenya buyers order most?",
        answer:
          "PUF cam-lock cold room panels for chiller and freezer rooms are the most common enquiry. PIR panels are requested when the buyer needs thinner walls for the same insulation value. Industrial roofing and wall panels for warehouses are the second most frequent category.",
      },
    ],
    draft: false,
    updatedAt: "2026-04-13",
  },
  {
    slug: "tanzania",
    name: "Tanzania",
    iso2: "TZ",
    region: "East Africa",
    h1: "Sandwich Panel Export to Tanzania",
    seoTitle: "Export Sandwich Panels to Tanzania | PHOENIXX",
    metaDescription:
      "PUF and PIR sandwich panels for Tanzania — Dar es Salaam port. Full country page coming soon.",
    portsOfEntry: ["Dar es Salaam"],
    majorCities: ["dar-es-salaam"],
    relevantProducts: ["puf-panels", "pir-panels", "cold-room-panels"],
    relevantIndustries: ["cold-storage", "food-processing", "warehousing-logistics"],
    industrialZones: [],
    demandDrivers: [],
    logisticsNotes: "",
    documentationNotes: "",
    faqs: [],
    holdingCopy:
      "We're publishing the full export page for Tanzania shortly — Dar es Salaam port logistics, import documentation and local demand sectors included. If you need a quotation now, send us your delivery city and we'll respond the same day.",
    draft: true,
  },
  {
    slug: "uganda",
    name: "Uganda",
    iso2: "UG",
    region: "East Africa",
    h1: "Sandwich Panel Export to Uganda",
    seoTitle: "Export Sandwich Panels to Uganda | PHOENIXX",
    metaDescription:
      "Insulated sandwich panels for Uganda — via Mombasa or Dar es Salaam. Full page coming soon.",
    portsOfEntry: ["Mombasa (transit)", "Dar es Salaam (transit)"],
    majorCities: ["kampala"],
    relevantProducts: ["puf-panels", "cold-room-panels"],
    relevantIndustries: ["cold-storage", "food-processing"],
    industrialZones: [],
    demandDrivers: [],
    logisticsNotes: "",
    documentationNotes: "",
    faqs: [],
    holdingCopy:
      "We're publishing the full export page for Uganda shortly — transit routes, border clearance and cold storage demand included. If you need a quotation now, send us your project details and we'll respond the same day.",
    draft: true,
  },
  {
    slug: "rwanda",
    name: "Rwanda",
    iso2: "RW",
    region: "East Africa",
    h1: "Sandwich Panel Export to Rwanda",
    seoTitle: "Export Sandwich Panels to Rwanda | PHOENIXX",
    metaDescription:
      "Insulated panels for Rwanda — via Mombasa and inland transit. Full page coming soon.",
    portsOfEntry: ["Mombasa (transit)"],
    majorCities: ["kigali"],
    relevantProducts: ["puf-panels", "cold-room-panels"],
    relevantIndustries: ["cold-storage", "food-processing"],
    industrialZones: [],
    demandDrivers: [],
    logisticsNotes: "",
    documentationNotes: "",
    faqs: [],
    holdingCopy:
      "We're publishing the full export page for Rwanda shortly — transit logistics via Mombasa, import procedures and project sectors included. If you need a quotation now, send us your delivery location and we'll respond the same day.",
    draft: true,
  },
  {
    slug: "ghana",
    name: "Ghana",
    iso2: "GH",
    region: "West Africa",
    h1: "Sandwich Panel Export to Ghana",
    seoTitle: "Export Sandwich Panels to Ghana | PHOENIXX",
    metaDescription:
      "PUF and PIR panels for Ghana — Tema port. Full export page coming soon.",
    portsOfEntry: ["Tema"],
    majorCities: ["accra", "tema"],
    relevantProducts: ["puf-panels", "pir-panels", "cold-room-panels"],
    relevantIndustries: ["cold-storage", "warehousing-logistics", "food-processing"],
    industrialZones: [],
    demandDrivers: [],
    logisticsNotes: "",
    documentationNotes: "",
    faqs: [],
    holdingCopy:
      "We're publishing the full export page for Ghana shortly — Tema port logistics, import documentation and industrial demand included. If you need a quotation now, send us your project details and we'll respond the same day.",
    draft: true,
  },
  {
    slug: "zambia",
    name: "Zambia",
    iso2: "ZM",
    region: "Southern Africa",
    h1: "Sandwich Panel Export to Zambia",
    seoTitle: "Export Sandwich Panels to Zambia | PHOENIXX",
    metaDescription:
      "Insulated panels for Zambia — via Dar es Salaam or Durban transit. Full page coming soon.",
    portsOfEntry: ["Dar es Salaam (transit)", "Durban (transit)"],
    majorCities: ["lusaka"],
    relevantProducts: ["puf-panels", "cold-room-panels", "roofing-panels"],
    relevantIndustries: ["cold-storage", "manufacturing-plants", "warehousing-logistics"],
    industrialZones: [],
    demandDrivers: [],
    logisticsNotes: "",
    documentationNotes: "",
    faqs: [],
    holdingCopy:
      "We're publishing the full export page for Zambia shortly — transit routes, mining sector demand and cold storage applications included. If you need a quotation now, send us your delivery city and we'll respond the same day.",
    draft: true,
  },
  {
    slug: "mozambique",
    name: "Mozambique",
    iso2: "MZ",
    region: "Southern Africa",
    h1: "Sandwich Panel Export to Mozambique",
    seoTitle: "Export Sandwich Panels to Mozambique | PHOENIXX",
    metaDescription:
      "Insulated panels for Mozambique — Maputo port. Full export page coming soon.",
    portsOfEntry: ["Maputo"],
    majorCities: ["maputo"],
    relevantProducts: ["puf-panels", "cold-room-panels"],
    relevantIndustries: ["cold-storage", "food-processing"],
    industrialZones: [],
    demandDrivers: [],
    logisticsNotes: "",
    documentationNotes: "",
    faqs: [],
    holdingCopy:
      "We're publishing the full export page for Mozambique shortly — Maputo port logistics and import procedures included. If you need a quotation now, send us your project details and we'll respond the same day.",
    draft: true,
  },
  {
    slug: "namibia",
    name: "Namibia",
    iso2: "NA",
    region: "Southern Africa",
    h1: "Sandwich Panel Export to Namibia",
    seoTitle: "Export Sandwich Panels to Namibia | PHOENIXX",
    metaDescription:
      "Insulated panels for Namibia — Walvis Bay port. Full page coming soon.",
    portsOfEntry: ["Walvis Bay"],
    majorCities: ["windhoek"],
    relevantProducts: ["puf-panels", "roofing-panels", "wall-panels"],
    relevantIndustries: ["warehousing-logistics", "cold-storage"],
    industrialZones: [],
    demandDrivers: [],
    logisticsNotes: "",
    documentationNotes: "",
    faqs: [],
    holdingCopy:
      "We're publishing the full export page for Namibia shortly — Walvis Bay port logistics and inland delivery included. If you need a quotation now, send us your project details and we'll respond the same day.",
    draft: true,
  },
  {
    slug: "botswana",
    name: "Botswana",
    iso2: "BW",
    region: "Southern Africa",
    h1: "Sandwich Panel Export to Botswana",
    seoTitle: "Export Sandwich Panels to Botswana | PHOENIXX",
    metaDescription:
      "Insulated panels for Botswana — via Durban or Walvis Bay transit. Full page coming soon.",
    portsOfEntry: ["Durban (transit)", "Walvis Bay (transit)"],
    majorCities: ["gaborone"],
    relevantProducts: ["puf-panels", "cold-room-panels"],
    relevantIndustries: ["cold-storage", "warehousing-logistics"],
    industrialZones: [],
    demandDrivers: [],
    logisticsNotes: "",
    documentationNotes: "",
    faqs: [],
    holdingCopy:
      "We're publishing the full export page for Botswana shortly — transit logistics and cold storage demand included. If you need a quotation now, send us your delivery location and we'll respond the same day.",
    draft: true,
  },
  {
    slug: "angola",
    name: "Angola",
    iso2: "AO",
    region: "Southern Africa",
    h1: "Sandwich Panel Export to Angola",
    seoTitle: "Export Sandwich Panels to Angola | PHOENIXX",
    metaDescription:
      "Insulated panels for Angola — Luanda port. Full export page coming soon.",
    portsOfEntry: ["Luanda"],
    majorCities: ["luanda"],
    relevantProducts: ["puf-panels", "cold-room-panels", "roofing-panels"],
    relevantIndustries: ["cold-storage", "food-processing", "warehousing-logistics"],
    industrialZones: [],
    demandDrivers: [],
    logisticsNotes: "",
    documentationNotes: "",
    faqs: [],
    holdingCopy:
      "We're publishing the full export page for Angola shortly — Luanda port logistics and import documentation included. If you need a quotation now, send us your project details and we'll respond the same day.",
    draft: true,
  },
  {
    slug: "ethiopia",
    name: "Ethiopia",
    iso2: "ET",
    region: "East Africa",
    h1: "Sandwich Panel Export to Ethiopia",
    seoTitle: "Export Sandwich Panels to Ethiopia | PHOENIXX",
    metaDescription:
      "Insulated panels for Ethiopia — via Djibouti port transit. Full page coming soon.",
    portsOfEntry: ["Djibouti (transit)"],
    majorCities: [],
    relevantProducts: ["puf-panels", "cold-room-panels"],
    relevantIndustries: ["cold-storage", "food-processing"],
    industrialZones: [],
    demandDrivers: [],
    logisticsNotes: "",
    documentationNotes: "",
    faqs: [],
    holdingCopy:
      "We're publishing the full export page for Ethiopia shortly — Djibouti transit logistics and import procedures included. If you need a quotation now, send us your delivery city and we'll respond the same day.",
    draft: true,
  },
  {
    slug: "nigeria",
    name: "Nigeria",
    iso2: "NG",
    region: "West Africa",
    h1: "Sandwich Panel Export to Nigeria",
    seoTitle: "Export Sandwich Panels to Nigeria | PHOENIXX",
    metaDescription:
      "Insulated panels for Nigeria — Lagos and Port Harcourt ports. Full page coming soon.",
    portsOfEntry: ["Lagos (Apapa/Tincan)", "Port Harcourt"],
    majorCities: [],
    relevantProducts: ["puf-panels", "pir-panels", "cold-room-panels"],
    relevantIndustries: ["cold-storage", "food-processing", "pharmaceutical-cleanroom"],
    industrialZones: [],
    demandDrivers: [],
    logisticsNotes: "",
    documentationNotes: "",
    faqs: [],
    holdingCopy:
      "We're publishing the full export page for Nigeria shortly — Lagos port logistics, SONCAP requirements and import documentation included. If you need a quotation now, send us your project details and we'll respond the same day.",
    draft: true,
  },
  {
    slug: "south-africa",
    name: "South Africa",
    iso2: "ZA",
    region: "Southern Africa",
    h1: "Sandwich Panel Export to South Africa",
    seoTitle: "Export Sandwich Panels to South Africa | PHOENIXX",
    metaDescription:
      "Insulated panels for South Africa — Durban, Cape Town, Port Elizabeth. Full page coming soon.",
    portsOfEntry: ["Durban", "Cape Town", "Port Elizabeth (Gqeberha)"],
    majorCities: [],
    relevantProducts: ["puf-panels", "pir-panels", "rockwool-panels", "roofing-panels"],
    relevantIndustries: ["cold-storage", "warehousing-logistics", "manufacturing-plants"],
    industrialZones: [],
    demandDrivers: [],
    logisticsNotes: "",
    documentationNotes: "",
    faqs: [],
    holdingCopy:
      "We're publishing the full export page for South Africa shortly — port options, SABS requirements and import documentation included. If you need a quotation now, send us your delivery port and we'll respond the same day.",
    draft: true,
  },
  {
    slug: "zimbabwe",
    name: "Zimbabwe",
    iso2: "ZW",
    region: "Southern Africa",
    h1: "Sandwich Panel Export to Zimbabwe",
    seoTitle: "Export Sandwich Panels to Zimbabwe | PHOENIXX",
    metaDescription:
      "Insulated panels for Zimbabwe — via Durban or Beira transit. Full page coming soon.",
    portsOfEntry: ["Durban (transit)", "Beira (transit)"],
    majorCities: [],
    relevantProducts: ["puf-panels", "cold-room-panels"],
    relevantIndustries: ["cold-storage", "food-processing"],
    industrialZones: [],
    demandDrivers: [],
    logisticsNotes: "",
    documentationNotes: "",
    faqs: [],
    holdingCopy:
      "We're publishing the full export page for Zimbabwe shortly — transit routes and import procedures included. If you need a quotation now, send us your delivery location and we'll respond the same day.",
    draft: true,
  },
  {
    slug: "mauritius",
    name: "Mauritius",
    iso2: "MU",
    region: "Indian Ocean",
    h1: "Sandwich Panel Export to Mauritius",
    seoTitle: "Export Sandwich Panels to Mauritius | PHOENIXX",
    metaDescription:
      "Insulated panels for Mauritius — Port Louis. Full export page coming soon.",
    portsOfEntry: ["Port Louis"],
    majorCities: [],
    relevantProducts: ["puf-panels", "pir-panels", "cold-room-panels"],
    relevantIndustries: ["cold-storage", "food-processing", "pharmaceutical-cleanroom"],
    industrialZones: [],
    demandDrivers: [],
    logisticsNotes: "",
    documentationNotes: "",
    faqs: [],
    holdingCopy:
      "We're publishing the full export page for Mauritius shortly — Port Louis logistics and import documentation included. If you need a quotation now, send us your project details and we'll respond the same day.",
    draft: true,
  },
  {
    slug: "drc",
    name: "Democratic Republic of Congo",
    iso2: "CD",
    region: "Central Africa",
    h1: "Sandwich Panel Export to DRC",
    seoTitle: "Export Sandwich Panels to DRC | PHOENIXX",
    metaDescription:
      "Insulated panels for DRC — via Dar es Salaam or Durban transit. Full page coming soon.",
    portsOfEntry: ["Dar es Salaam (transit)", "Durban (transit)"],
    majorCities: [],
    relevantProducts: ["puf-panels", "cold-room-panels"],
    relevantIndustries: ["cold-storage", "manufacturing-plants", "food-processing"],
    industrialZones: [],
    demandDrivers: [],
    logisticsNotes: "",
    documentationNotes: "",
    faqs: [],
    holdingCopy:
      "We're publishing the full export page for DRC shortly — transit logistics via East and Southern African ports included. If you need a quotation now, send us your delivery city and we'll respond the same day.",
    draft: true,
  },
];
